"""empty message

Revision ID: 3ea62ae32e70
Revises: 1d8c249b8086
Create Date: 2014-01-26 05:04:04.127307

"""

# revision identifiers, used by Alembic.
revision = '3ea62ae32e70'
down_revision = '1d8c249b8086'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    ### end Alembic commands ###
